# Generated by Django 4.2.7 on 2025-04-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
