# Generated by Django 4.2.7 on 2025-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre_artistalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='api.ArtistAlbum', to='api.artist'),
        ),
    ]
